from pydantic import BaseModel, EmailStr, Field
from typing import List, Optional, Dict, Any
from datetime import datetime

# ==========================================
# 1. Authentication & User Management (FR1)
# ==========================================
# [cite_start]Citations: [cite: 16]
class UserRegister(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    email: EmailStr
    password: str = Field(..., min_length=8)

class UserLogin(BaseModel):
    username: str
    password: str

class Token(BaseModel):
    access_token: str
    token_type: str

class UserProfileResponse(BaseModel):
    username: str
    email: EmailStr
    preferences: Optional[Dict[str, Any]] = None

# ==========================================
# 2. Email Processing (FR2)
# ==========================================
# [cite_start]Citations: [cite: 18]
class EmailPayload(BaseModel):
    """Input for reading incoming emails."""
    message_id: str
    sender: str
    subject: str
    body: str
    received_at: datetime
    metadata: Optional[Dict[str, Any]] = None

class EmailActionItem(BaseModel):
    """Structured action extracted from an email."""
    action_type: str = Field(..., description="e.g., Reply, Task, Booking")
    description: str
    priority: str = Field(..., description="High, Medium, Low")
    suggested_response: Optional[str] = None

class EmailAnalysisResponse(BaseModel):
    """Output after LLM analysis of the email."""
    email_id: str
    intent: str
    summary: str
    required_actions: List[EmailActionItem]
    priority_score: int = Field(..., ge=1, le=10)

# ==========================================
# 3. Reasoning & Task Planning (FR3, FR4)
# ==========================================
# [cite_start]Citations: [cite: 23, 24]
class GoalRequest(BaseModel):
    """User's high-level objective."""
    objective: str = Field(..., example="Plan a business trip to London next week")
    constraints: Optional[Dict[str, Any]] = Field(default=None, description="Time, Budget, Preferences")

class SubTask(BaseModel):
    """A single step in a generated plan."""
    step_number: int
    description: str
    tool_required: Optional[str] = Field(None, description="e.g., CalendarAPI, BookingAPI")
    estimated_duration: str
    status: str = "pending"

class ExecutionPlanResponse(BaseModel):
    """The decomposed plan generated by the Reasoner."""
    plan_id: str
    goal: str
    tasks: List[SubTask]
    total_estimated_time: str

# ==========================================
# 4. Service Booking (FR5)
# ==========================================
# [cite_start]Citations: [cite: 29]
class BookingCriteria(BaseModel):
    service_type: str = Field(..., description="flight, hotel, restaurant")
    location: str
    date_range: Dict[str, datetime]
    budget_max: Optional[float] = None
    preferences: List[str] = []

class BookingOption(BaseModel):
    """A found option presented to the user."""
    provider_name: str
    price: float
    rating: Optional[float] = None
    details: Dict[str, Any]
    booking_url: Optional[str] = None

# ==========================================
# 5. Context & Chat (FR6)
# ==========================================
# [cite_start]Citations: [cite: 30]
class ChatMessage(BaseModel):
    role: str = Field(..., description="user or assistant")
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)