from datetime import datetime
from typing import Literal, List, Optional
from pydantic import BaseModel, Field


class Recommendation(BaseModel):
    """A single contextual recommendation card generated by the LLM."""

    title: str = Field(
        ...,
        description="Short, actionable recommendation title — 10 words or fewer."
    )
    body: str = Field(
        ...,
        description=(
            "1-2 sentence explanation of why this recommendation is relevant "
            "right now, referencing the user's mood or upcoming events where possible."
        )
    )
    category: Literal["wellbeing", "productivity", "focus", "social", "break"] = Field(
        ...,
        description="Category that best describes the type of recommendation."
    )
    priority: int = Field(
        ...,
        ge=1,
        le=5,
        description="Priority score from 1 (low) to 5 (urgent)."
    )
    icon: str = Field(
        ...,
        description="A single emoji that visually represents the recommendation."
    )


class RecommendationList(BaseModel):
    """Container returned by the LLM — enforces 3-6 recommendations."""

    recommendations: List[Recommendation] = Field(
        ...,
        min_length=3,
        max_length=6,
        description="List of 3 to 6 personalised recommendations for the user."
    )


class RecommendationResponse(BaseModel):
    """API response shape returned to the frontend dashboard."""

    title: str
    body: str
    category: str
    priority: int
    icon: str
    generated_at: Optional[datetime] = None
    user_id: Optional[str] = None
